#!/usr/bin/env python3
"""Regenerates jni/graphics/EmbeddedGlShader.h from TESTLIT/graphics/glShader/.

The engine reads glShader/ files from /storage/emulated/0/TESTLIT/graphics/;
these built-in copies are only used when a file is missing there.
Run after editing any .shader file:  python3 tools/embed_glshader.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "TESTLIT", "graphics", "glShader")
DST = os.path.join(ROOT, "jni", "graphics", "EmbeddedGlShader.h")
DELIM = "GLSH"


def main():
    files = []
    for base, _, names in os.walk(SRC):
        for name in names:
            if name.endswith(".shader"):
                full = os.path.join(base, name)
                files.append(os.path.relpath(full, SRC).replace(os.sep, "/"))
    files.sort()
    out = [
        "#pragma once",
        "// GENERATED by tools/embed_glshader.py from TESTLIT/graphics/glShader/ - do not edit.",
        "// Built-in copies of the glShader/ files: a file in",
        "// /storage/emulated/0/TESTLIT/graphics/glShader/ always wins.",
        "",
        '#include "ShaderManager.h"',
        "",
        "namespace gfx {",
        "",
        "struct EmbeddedGlShaderFile {",
        "    const char* path;",
        "    const char* source;",
        "};",
        "",
        "inline constexpr EmbeddedGlShaderFile kEmbeddedGlShader[] = {",
    ]
    for rel in files:
        with open(os.path.join(SRC, rel), encoding="utf-8") as f:
            text = f.read().replace("\r\n", "\n")
        if ")" + DELIM + '"' in text:
            sys.exit("delimiter clash in " + rel)
        out.append('    {"%s", R"%s(%s)%s"},' % (rel, DELIM, text, DELIM))
    out += [
        "};",
        "",
        "inline void RegisterEmbeddedShaders(ShaderManager& sm) {",
        "    for (const EmbeddedGlShaderFile& f : kEmbeddedGlShader) sm.RegisterEmbedded(f.path, f.source);",
        "}",
        "",
        "} // namespace gfx",
        "",
    ]
    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote %s (%d files)" % (os.path.relpath(DST, ROOT), len(files)))


if __name__ == "__main__":
    main()
