#pragma once
// GENERATED by tools/embed_glshader.py from TESTLIT/graphics/glShader/ - do not edit.
// Built-in copies of the glShader/ files: a file in
// /storage/emulated/0/TESTLIT/graphics/glShader/ always wins.

#include "ShaderManager.h"

namespace gfx {

struct EmbeddedGlShaderFile {
    const char* path;
    const char* source;
};

inline constexpr EmbeddedGlShaderFile kEmbeddedGlShader[] = {
    {"Debug/Cascade.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/Debug/Cascade.shader
//  [debug] showCascade = 1 (Advanced.ini atau tab Grafis): warnai penerima
//  per cascade - merah / hijau / biru / kuning.
// =====================================================================
<frag>
void SG_DebugCascade(inout lowp vec4 color, highp float vis) {
    if (SG_Boost.a > 0.5) {
        highp float d = SG_vDepth;
        mediump vec3 cc = d < SG_Split.x ? vec3(1.0, 0.35, 0.35) : (d < SG_Split.y ? vec3(0.35, 1.0, 0.35) : (d < SG_Split.z ? vec3(0.35, 0.45, 1.0) : vec3(1.0, 1.0, 0.35)));
        color.rgb = mix(color.rgb, cc * (0.35 + 0.65 * vis), 0.5);
    }
}
</frag>
)GLSH"},
    {"Debug/ShadowMap.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/Debug/ShadowMap.shader
//  [debug] showShadowMap = 1: gambar shadow atlas di kiri bawah layar
//  (dekat = gelap, kosong = putih). Program milik engine (GLSL ES 3.00),
//  bukan shader GTA. Bisa dimuat ulang tanpa restart (nativeReloadShaders).
// =====================================================================
<vert>
#version 300 es
layout(location = 0) in vec2 aPosition;
uniform vec4 uRect; // NDC x0, y0, x1, y1
out vec2 vUV;
void main() {
    vUV = aPosition;
    gl_Position = vec4(mix(uRect.xy, uRect.zw, aPosition), 0.0, 1.0);
}
</vert>

<frag>
#version 300 es
precision highp float;
uniform highp sampler2D uDepth;
in vec2 vUV;
out vec4 fragColor;
void main() {
    float d = texture(uDepth, vUV).r;
    float v = d >= 0.9999 ? 1.0 : pow(d, 3.0);
    fragColor = vec4(v, v * 0.97, v * 0.92, 1.0);
}
</frag>
)GLSH"},
    {"Depth/Caster.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/Depth/Caster.shader
//  Pass caster (render ke shadow map). Semua cascade memakai shader GTA
//  sendiri (skinning, alpha test, format vertex asli) dengan SG_Light.w < 0;
//  fungsi ini dipanggil oleh SG_Apply pada pass tersebut.
//  Warna tidak ditulis (atlas hanya depth): yang penting hanya discard.
// =====================================================================
<frag>
void SG_Caster(inout lowp vec4 color) {
#if SG_ALPHA
    if (color.a < SG_Bias.w) discard;
#endif
}
</frag>
)GLSH"},
    {"Entity/Building.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/Entity/Building.shader
//  Cara gedung, jalan, pohon dan objek dunia menerima bayangan matahari.
//  Dipakai untuk semua shader dunia GTA yang bukan kendaraan dan bukan ped.
//  Wajib mendefinisikan: void SG_Apply(inout lowp vec4 color)
// =====================================================================
<frag>
#include "realtimeShadow.shader";
#include "Depth/Caster.shader";
#include "Debug/Cascade.shader";

@float Building_ShadowStrength < class = "Building", name = "ShadowStrength", default = 1.0; min = 0.0; max = 1.5; step = 0.05; >
@float Building_SunBoost < class = "Building", name = "SunBoost", default = 1.0; min = 0.0; max = 3.0; step = 0.05; >

void SG_Apply(inout lowp vec4 color) {
    SG_SpecVis = 1.0;
    if (SG_Light.w < 0.0) {
        SG_Caster(color);
        return;
    }
    if (SG_Light.w <= 0.0) return;
    mediump float nl;
    highp float vis = SG_SunVisibility(nl);
    SG_SpecVis = vis;
    SG_Shade(color, vis, nl, Building_ShadowStrength, Building_SunBoost);
    SG_DebugCascade(color, vis);
}
</frag>
)GLSH"},
    {"Entity/Character.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/Entity/Character.shader
//  Cara ped/pemain menerima bayangan matahari (shader GTA dengan skinning).
//  MinLight menjaga wajah tetap terbaca di bawah bayangan gedung.
//  Wajib mendefinisikan: void SG_Apply(inout lowp vec4 color)
// =====================================================================
<frag>
#include "realtimeShadow.shader";
#include "Depth/Caster.shader";
#include "Debug/Cascade.shader";

@float Character_ShadowStrength < class = "Character", name = "ShadowStrength", default = 0.85; min = 0.0; max = 1.5; step = 0.05; >
@float Character_SunBoost < class = "Character", name = "SunBoost", default = 1.0; min = 0.0; max = 3.0; step = 0.05; >
@float Character_MinLight < class = "Character", name = "MinLight", default = 0.15; min = 0.0; max = 1.0; step = 0.05; >

void SG_Apply(inout lowp vec4 color) {
    SG_SpecVis = 1.0;
    if (SG_Light.w < 0.0) {
        SG_Caster(color);
        return;
    }
    if (SG_Light.w <= 0.0) return;
    mediump float nl;
    highp float vis = max(SG_SunVisibility(nl), Character_MinLight);
    SG_SpecVis = vis;
    SG_Shade(color, vis, nl, Character_ShadowStrength, Character_SunBoost);
    SG_DebugCascade(color, vis);
}
</frag>
)GLSH"},
    {"Entity/Vehicle.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/Entity/Vehicle.shader
//  Cara kendaraan menerima bayangan matahari (shader GTA dengan
//  env-map + specular). Specular (kilap matahari) ikut redup di bayangan.
//  Wajib mendefinisikan: void SG_Apply(inout lowp vec4 color)
// =====================================================================
<frag>
#include "realtimeShadow.shader";
#include "Depth/Caster.shader";
#include "Debug/Cascade.shader";

@float Vehicle_ShadowStrength < class = "Vehicle", name = "ShadowStrength", default = 0.9; min = 0.0; max = 1.5; step = 0.05; >
@float Vehicle_SunBoost < class = "Vehicle", name = "SunBoost", default = 1.0; min = 0.0; max = 3.0; step = 0.05; >
@float Vehicle_SpecularInShadow < class = "Vehicle", name = "SpecularInShadow", default = 0.1; min = 0.0; max = 1.0; step = 0.05; >

void SG_Apply(inout lowp vec4 color) {
    SG_SpecVis = 1.0;
    if (SG_Light.w < 0.0) {
        SG_Caster(color);
        return;
    }
    if (SG_Light.w <= 0.0) return;
    mediump float nl;
    highp float vis = SG_SunVisibility(nl);
    SG_SpecVis = mix(Vehicle_SpecularInShadow, 1.0, vis);
    SG_Shade(color, vis, nl, Vehicle_ShadowStrength, Vehicle_SunBoost);
    SG_DebugCascade(color, vis);
}
</frag>
)GLSH"},
    {"realtimeShadow.shader", R"GLSH(// =====================================================================
//  EAGLE Graphics - glShader/realtimeShadow.shader
//  Penerima bayangan matahari: pilih cascade + PCF.
//  Di-#include oleh Entity/Building.shader, Vehicle.shader, Character.shader.
//
//  Kode ini DISUNTIKKAN ke shader dunia milik GTA (GLSL ES 1.00), tepat
//  sebelum "void main()". Engine menambahkan define:
//    SG_HW    1 = sampler2DShadow (GL_EXT_shadow_samplers), 0 = compare manual
//    SG_TAPS  1, 4 atau 9 tap PCF
//    SG_BLEND 1 = band blend antar cascade
//    SG_LIT   1 = shader GTA ber-lighting (ped/kendaraan/objek), SG_vDirect ada
//    SG_ALPHA 1 = shader alpha-test (daun/pagar)
//
//  Aturan:
//   - Setiap statement < 400 karakter (GTA mencetak shader yang gagal per
//     statement ke buffer 520 byte).
//   - Parameter @ hanya boleh dipakai di dalam fungsi (diisi oleh
//     SG_InitUser() di awal main).
//   - GTA mengompilasi shader sekali saat start: ubah file ini = restart game.
//     Nilai @ di shaderUniform.ini berubah LANGSUNG (tanpa restart).
// =====================================================================
<frag>
@float Shadow_Strength < class = "Shadow", name = "Strength", default = 1.0; min = 0.0; max = 1.5; step = 0.05; >
@float Shadow_Softness < class = "Shadow", name = "Softness", default = 1.0; min = 0.25; max = 3.0; step = 0.05; >

#if SG_HW
uniform mediump sampler2DShadow SG_ShadowMap;
#else
uniform highp sampler2D SG_ShadowMap;
#endif
uniform highp mat4 SG_VP[4];
uniform highp vec4 SG_Tile[4];
uniform highp vec4 SG_Split;
uniform highp vec4 SG_Cfg;
uniform highp vec4 SG_Bias;
uniform highp vec4 SG_DBias;
uniform highp vec4 SG_Texel;
uniform mediump vec4 SG_Light;
uniform mediump vec4 SG_Tint;
uniform mediump vec4 SG_Boost;
varying highp vec3 SG_vWorld;
varying highp float SG_vDepth;
varying mediump vec3 SG_vNormal;
#if SG_LIT
varying lowp vec3 SG_vDirect;
#endif
highp float SG_SpecVis;

// SG_Cfg   : x = 1/lebar atlas, y = 1/tinggi atlas, z = awal fade, w = akhir fade (kedalaman view, meter)
// SG_Bias  : x = normal offset (texel), y = band blend (fraksi), z = jarak tap PCF (texel), w = alpha cutoff caster
// SG_Light : xyz = arah ke matahari, w > 0 kekuatan bayangan, 0 = mati, < 0 = pass caster
// SG_Tint  : rgb = warna di bayangan penuh, a = porsi cahaya matahari pada warna prelit
// SG_Boost : rgb = tambahan cahaya matahari, a = 1 debug warna cascade

highp float SG_Cmp(highp vec2 uv, highp float z) {
#if SG_HW
    return shadow2DEXT(SG_ShadowMap, vec3(uv, z));
#else
    return step(z, texture2D(SG_ShadowMap, uv).r);
#endif
}

highp float SG_Pcf(highp vec4 tile, highp vec3 c, highp float bias) {
    highp float z = min(c.z - bias, 1.0);
    highp vec2 o = SG_Cfg.xy * (SG_Bias.z * Shadow_Softness);
#if SG_TAPS == 1
    return SG_Cmp(clamp(c.xy, tile.xy, tile.zw), z);
#elif SG_TAPS == 4
    highp vec2 h = o * 0.5;
    highp float s = SG_Cmp(clamp(c.xy + vec2(-h.x, -h.y), tile.xy, tile.zw), z);
    s += SG_Cmp(clamp(c.xy + vec2(h.x, -h.y), tile.xy, tile.zw), z);
    s += SG_Cmp(clamp(c.xy + vec2(-h.x, h.y), tile.xy, tile.zw), z);
    s += SG_Cmp(clamp(c.xy + vec2(h.x, h.y), tile.xy, tile.zw), z);
    return s * 0.25;
#else
    highp float s = 0.0;
    for (int y = -1; y <= 1; ++y) {
        for (int x = -1; x <= 1; ++x) {
            s += SG_Cmp(clamp(c.xy + vec2(float(x), float(y)) * o, tile.xy, tile.zw), z);
        }
    }
    return s * (1.0 / 9.0);
#endif
}

highp float SG_C0(mediump vec3 n) { return SG_Pcf(SG_Tile[0], (SG_VP[0] * vec4(SG_vWorld + n * (SG_Bias.x * SG_Texel.x), 1.0)).xyz, SG_DBias.x); }
highp float SG_C1(mediump vec3 n) { return SG_Pcf(SG_Tile[1], (SG_VP[1] * vec4(SG_vWorld + n * (SG_Bias.x * SG_Texel.y), 1.0)).xyz, SG_DBias.y); }
highp float SG_C2(mediump vec3 n) { return SG_Pcf(SG_Tile[2], (SG_VP[2] * vec4(SG_vWorld + n * (SG_Bias.x * SG_Texel.z), 1.0)).xyz, SG_DBias.z); }
highp float SG_C3(mediump vec3 n) { return SG_Pcf(SG_Tile[3], (SG_VP[3] * vec4(SG_vWorld + n * (SG_Bias.x * SG_Texel.w), 1.0)).xyz, SG_DBias.w); }

// Cascade dipilih dari kedalaman view; band blend menghaluskan pergantian cascade.
highp float SG_Visibility(mediump vec3 n) {
    highp float d = SG_vDepth;
    if (d >= SG_Cfg.w) return 1.0;
    highp float v;
    if (d < SG_Split.x) {
        v = SG_C0(n);
#if SG_BLEND
        highp float b = SG_Split.x * SG_Bias.y;
        if (d > SG_Split.x - b) v = mix(v, SG_C1(n), (d - (SG_Split.x - b)) / b);
#endif
    } else if (d < SG_Split.y) {
        v = SG_C1(n);
#if SG_BLEND
        highp float b = SG_Split.y * SG_Bias.y;
        if (d > SG_Split.y - b) v = mix(v, SG_C2(n), (d - (SG_Split.y - b)) / b);
#endif
    } else if (d < SG_Split.z) {
        v = SG_C2(n);
#if SG_BLEND
        highp float b = SG_Split.z * SG_Bias.y;
        if (d > SG_Split.z - b) v = mix(v, SG_C3(n), (d - (SG_Split.z - b)) / b);
#endif
    } else {
        v = SG_C3(n);
    }
    return mix(v, 1.0, smoothstep(SG_Cfg.z, SG_Cfg.w, d));
}

// Visibilitas matahari piksel ini (0 = bayangan penuh) dan N.L ke arah matahari.
highp float SG_SunVisibility(out mediump float nl) {
    mediump vec3 n = SG_vNormal;
    nl = 1.0;
    mediump float len2 = dot(n, n);
    if (len2 > 0.01) {
        n *= inversesqrt(len2);
        nl = dot(n, SG_Light.xyz);
    } else {
        n = vec3(0.0);
    }
    return min(SG_Visibility(n), smoothstep(-0.03, 0.22, nl));
}

// Porsi cahaya piksel ini yang berasal dari matahari (shader lit tahu persis).
mediump float SG_SunShare() {
#if SG_LIT
    return clamp(dot(SG_vDirect, vec3(0.3333)) / max(dot(Out_Color.rgb, vec3(0.3333)), 0.04), 0.0, 1.0);
#else
    return SG_Tint.a;
#endif
}

// Gelapkan sesuai bayangan, tambahkan cahaya matahari di bagian yang terkena.
void SG_Shade(inout lowp vec4 color, highp float vis, mediump float nl, mediump float strength, mediump float boost) {
    mediump float sh = clamp((1.0 - vis) * SG_Light.w * SG_SunShare() * strength * Shadow_Strength, 0.0, 1.0);
    color.rgb *= mix(vec3(1.0), SG_Tint.rgb, sh);
    color.rgb *= vec3(1.0) + SG_Boost.rgb * (vis * max(nl, 0.0) * boost);
}
</frag>
)GLSH"},
};

inline void RegisterEmbeddedShaders(ShaderManager& sm) {
    for (const EmbeddedGlShaderFile& f : kEmbeddedGlShader) sm.RegisterEmbedded(f.path, f.source);
}

} // namespace gfx
