#!/usr/bin/env python3
"""Regenerates ShaderSources.h from shaders/*. Run from any directory:
    python3 graphics/postfx/embed_shaders.py
#include "file" lines are inlined (one level, relative to shaders/)."""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "shaders")
OUT = os.path.join(HERE, "ShaderSources.h")
TABLE = [
    ("kVertex", "fullscreen.vert"),
    ("kDownsample", "downsample.frag"),
    ("kBlur", "blur.frag"),
    ("kDepthEffects", "depth_effects.frag"),
    ("kComposite", "composite.frag"),
    ("kAtmosphere", "atmosphere.frag"),
    ("kState", "state.frag"),
    ("kCompatVertex", "compat_fullscreen.vert"),
    ("kCompatBloom", "compat_bloom.frag"),
    ("kCompatComposite", "compat_composite.frag"),
    ("kCompatAtmosphere", "compat_atmosphere.frag"),
]
INCLUDE = re.compile(r'^\s*#include\s+"([^"]+)"\s*$')

def expand(name):
    out = []
    with open(os.path.join(SRC, name), encoding="utf-8") as f:
        for line in f.read().splitlines():
            m = INCLUDE.match(line)
            if m:
                with open(os.path.join(SRC, m.group(1)), encoding="utf-8") as inc:
                    out.append(inc.read())
            else:
                out.append(line)
    text = "\n".join(out) + "\n"
    if ')GLSL"' in text:
        sys.exit(name + ": contains the raw-string terminator")
    return text

def main():
    parts = ["// Generated by graphics/postfx/embed_shaders.py. Edit shaders/*, then regenerate.\n",
             "#pragma once\nnamespace EglPostFX::Shaders {\n"]
    for symbol, name in TABLE:
        parts.append('inline constexpr char %s[] = R"GLSL(%s)GLSL";\n' % (symbol, expand(name)))
    parts.append("}\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("".join(parts))

if __name__ == "__main__":
    main()
