// Generated by graphics/postfx/embed_shaders.py. Edit shaders/*, then regenerate.
#pragma once
namespace EglPostFX::Shaders {
inline constexpr char kVertex[] = R"GLSL(#version 300 es
precision highp float;
out highp vec2 vUV;
void main() {
    // Satu fullscreen triangle: cakupan sama dengan quad, tanpa diagonal seam/VBO.
    vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));
    vUV = p;
    gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);
}
)GLSL";
inline constexpr char kDownsample[] = R"GLSL(#version 300 es
precision highp float;
in highp vec2 vUV;
layout(location=0) out vec4 outColor;
uniform sampler2D uSource;
uniform vec2 uTexel;
uniform int uDecodeSRGB;
uniform int uExtract;
uniform vec2 uThresholdKnee;
vec3 linearRGB(vec3 c) {
    return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)),
               step(vec3(0.04045), c));
}
vec3 tap(vec2 p) {
    vec3 c = texture(uSource, p).rgb;
    c=uDecodeSRGB != 0 ? linearRGB(c) : c;
    // Extract before filtering so thin lamp highlights are not averaged away.
    if(uExtract!=0) {
        float b=max(c.r,max(c.g,c.b));
        float knee=max(uThresholdKnee.y,0.0001);
        float soft=clamp(b-uThresholdKnee.x+knee,0.0,2.0*knee);
        c*=max(b-uThresholdKnee.x,soft*soft/(4.0*knee))/max(b,0.0001);
    }
    return c;
}
// Karis weight for the first (extract) level: one very bright pixel cannot
// dominate a texel, so small glints/coronas do not pulse as they move.
float karis(vec3 c) { return uExtract!=0 ? 1.0/(1.0+max(c.r,max(c.g,c.b))) : 1.0; }
vec3 sum; float weight;
void add(vec2 p,float k) { vec3 c=tap(p);float w=karis(c)*k;sum+=c*w;weight+=w; }
void main() {
    // 13-tap tent downsample; stabil saat highlight kecil bergerak.
    sum=vec3(0.0);weight=0.0;
    add(vUV,0.125);
    add(vUV+uTexel*vec2(-2,-2),0.03125);add(vUV+uTexel*vec2(2,-2),0.03125);
    add(vUV+uTexel*vec2(-2, 2),0.03125);add(vUV+uTexel*vec2(2, 2),0.03125);
    add(vUV+uTexel*vec2(-2,0),0.0625);add(vUV+uTexel*vec2(2,0),0.0625);
    add(vUV+uTexel*vec2(0,-2),0.0625);add(vUV+uTexel*vec2(0,2),0.0625);
    add(vUV+uTexel*vec2(-1,-1),0.125);add(vUV+uTexel*vec2(1,-1),0.125);
    add(vUV+uTexel*vec2(-1, 1),0.125);add(vUV+uTexel*vec2(1, 1),0.125);
    outColor = vec4(sum/max(weight,1e-5), 1.0);
}
)GLSL";
inline constexpr char kBlur[] = R"GLSL(#version 300 es
precision highp float;
in highp vec2 vUV;
layout(location=0) out vec4 outColor;
uniform sampler2D uSource;
uniform vec2 uDirection;
void main() {
    // Gaussian separable; 5 bilinear fetch setara kernel 9 tap.
    vec3 c = texture(uSource,vUV).rgb * 0.2270270270;
    c += (texture(uSource,vUV+uDirection*1.3846153846).rgb
        + texture(uSource,vUV-uDirection*1.3846153846).rgb) * 0.3162162162;
    c += (texture(uSource,vUV+uDirection*3.2307692308).rgb
        + texture(uSource,vUV-uDirection*3.2307692308).rgb) * 0.0702702703;
    outColor = vec4(c,1.0);
}
)GLSL";
inline constexpr char kDepthEffects[] = R"GLSL(#version 300 es
precision highp float;
precision highp sampler2D;
in highp vec2 vUV;
layout(location=0) out vec4 outColor; // RGB=SSR linear, A=AO.
uniform sampler2D uScene;
uniform sampler2D uDepth;
uniform mat4 uProjection;
uniform mat4 uInvProjection;
uniform vec2 uDepthRange;
uniform vec2 uTexel;
uniform float uClearDepth;
uniform float uForwardSign;
uniform int uSSR;
uniform int uAO;
uniform int uDecodeSRGB;
uniform vec4 uSSRParams; // strength, distance, thickness, unused.
uniform vec2 uAOParams;  // strength, radius.

bool sky(float d) { return abs(d-uClearDepth) < 0.0000002; }
bool inside(vec2 uv) { return all(greaterThan(uv,vec2(0.001))) && all(lessThan(uv,vec2(0.999))); }
vec3 positionAt(vec2 uv) {
    float d = texture(uDepth,uv).r;
    float z = (d-uDepthRange.x)/(uDepthRange.y-uDepthRange.x)*2.0-1.0;
    vec4 p = uInvProjection * vec4(uv*2.0-1.0,z,1.0);
    return p.xyz / (abs(p.w)>1e-7 ? p.w : (p.w<0.0 ? -1e-7 : 1e-7));
}
bool projectPoint(vec3 p, out vec2 uv) {
    vec4 h = uProjection*vec4(p,1.0);
    if (h.w <= 0.0001) return false;
    vec3 ndc = h.xyz/h.w;
    uv = ndc.xy*0.5+0.5;
    return inside(uv) && ndc.z>-1.0 && ndc.z<1.0;
}
vec3 normalAt(vec2 uv, vec3 p) {
    vec3 r=positionAt(uv+vec2(uTexel.x,0)), l=positionAt(uv-vec2(uTexel.x,0));
    vec3 t=positionAt(uv+vec2(0,uTexel.y)), b=positionAt(uv-vec2(0,uTexel.y));
    vec3 dx=abs(r.z-p.z)<abs(p.z-l.z) ? r-p : p-l;
    vec3 dy=abs(t.z-p.z)<abs(p.z-b.z) ? t-p : p-b;
    vec3 n=cross(dx,dy);
    n=dot(n,n)>1e-12 ? normalize(n) : normalize(-p);
    return dot(n,-p)<0.0 ? -n : n;
}
vec3 sampleScene(vec2 uv) {
    vec3 c=texture(uScene,uv).rgb;
    if(uDecodeSRGB!=0)
        c=mix(c/12.92,pow((c+0.055)/1.055,vec3(2.4)),step(vec3(0.04045),c));
    return c;
}
float ambientOcclusion(vec3 p,vec3 n) {
    float radius=max(uAOParams.y,0.01);
    float pixelRadius=clamp(abs(uProjection[1][1])*radius/max(abs(p.z),0.1)*0.5/uTexel.y,2.0,48.0);
    float occ=0.0;
    for(int i=0;i<8;++i) {
        float a=float(i)*2.39996323;
        vec2 uv=vUV+vec2(cos(a),sin(a))*uTexel*pixelRadius*(0.3+0.7*float(i+1)/8.0);
        if(!inside(uv) || sky(texture(uDepth,uv).r)) continue;
        vec3 delta=positionAt(uv)-p;
        float dist=length(delta);
        if(dist<0.001) continue;
        float range=1.0-smoothstep(radius*0.2,radius,dist);
        occ+=max(dot(n,delta/dist)-0.12,0.0)*range;
    }
    return clamp(1.0-uAOParams.x*occ/4.0,0.25,1.0);
}
vec3 reflections(vec3 p,vec3 n) {
    vec3 ray=reflect(normalize(p),n);
    float stride=uSSRParams.y/32.0;
    vec3 origin=p+n*max(0.02,abs(p.z)*0.0005);
    float prevT=0.0,prevDelta=-1.0;
    for(int i=1;i<=32;++i) {
        float t=float(i)*stride;
        vec3 q=origin+ray*t;
        vec2 uv;
        if(!projectPoint(q,uv)) break;
        if(sky(texture(uDepth,uv).r)) { prevT=t; prevDelta=-1.0; continue; }
        float delta=(q.z-positionAt(uv).z)*uForwardSign;
        if(i>1 && delta>=0.0 && prevDelta<0.0) {
            float lo=prevT,hi=t;
            for(int j=0;j<5;++j) {
                float mid=(lo+hi)*0.5;
                vec3 m=origin+ray*mid;
                vec2 mUV;
                if(!projectPoint(m,mUV)) break;
                float md=(m.z-positionAt(mUV).z)*uForwardSign;
                if(md>=0.0) hi=mid; else lo=mid;
            }
            vec3 hit=origin+ray*hi;
            vec2 hUV;
            if(projectPoint(hit,hUV)) {
                float err=(hit.z-positionAt(hUV).z)*uForwardSign;
                if(!sky(texture(uDepth,hUV).r) && err>=0.0 && err<uSSRParams.z) {
                    float edge=smoothstep(0.0,0.08,min(min(hUV.x,hUV.y),min(1.0-hUV.x,1.0-hUV.y)));
                    float fresnel=0.04+0.96*pow(1.0-clamp(dot(n,normalize(-p)),0.0,1.0),5.0);
                    return sampleScene(hUV)*edge*fresnel*uSSRParams.x*(1.0-hi/uSSRParams.y);
                }
            }
        }
        prevDelta=delta;prevT=t;
    }
    return vec3(0.0); // SSR murni: tidak mengarang refleksi objek di luar layar.
}
void main() {
    float d=texture(uDepth,vUV).r;
    if(sky(d)) { outColor=vec4(0,0,0,1); return; }
    vec3 p=positionAt(vUV);
    vec3 n=normalAt(vUV,p);
    vec3 refl=uSSR!=0 ? reflections(p,n) : vec3(0.0);
    float ao=uAO!=0 ? ambientOcclusion(p,n) : 1.0;
    outColor=vec4(refl,ao);
}
)GLSL";
inline constexpr char kComposite[] = R"GLSL(#version 300 es
precision highp float;
precision highp sampler2D;
in highp vec2 vUV;
layout(location=0) out vec4 outColor;
uniform sampler2D uScene;
uniform sampler2D uBloom0;
uniform sampler2D uBloom1;
uniform sampler2D uBloom2;
uniform sampler2D uEffects;
uniform sampler2D uDepth;
uniform sampler2D uDirt;
uniform sampler2D uAtmosphere;
uniform int uHasDepth;
uniform int uDecodeSRGB;
uniform int uEncodeSRGB;
uniform vec4 uGrade; // exposure, saturation, contrast, toneMix.
uniform vec2 uBloomDirt;
uniform vec2 uEffectSize;
uniform vec2 uDepthRange;
uniform mat4 uInvProjection;
uniform int uLightCount;
uniform vec4 uLightPosition[4]; // uv, radius, intensity.
uniform vec4 uLightColor[4]; // RGB, pulse amplitude.
uniform float uTime;
uniform float uAspect;
uniform vec4 uDetail,uFog;
uniform vec3 uShadowTint,uHighlightTint;
uniform vec2 uTexel;
uniform float uClearDepth;
// World-space data; all zero (effects off) when the camera is unknown.
uniform mat4 uInvView;      // camera -> GTA world (Z up)
uniform vec4 uSunDirection; // world direction to the sun, w = visibility
uniform vec4 uSkyZenith;    // rgb, w = sky tint strength
uniform vec4 uSkyHorizon;   // rgb, w = horizon haze
uniform vec4 uSunColor;     // rgb, w = sun glow strength
uniform vec4 uWet;          // wetness, rain, puddle coverage, reflection boost
uniform vec2 uDepthTexel;   // 1 / depth texture size
uniform int uFXAA;          // 1 = FXAA on the world image (HUD is drawn later)
vec3 linearRGB(vec3 c) {
    return mix(c/12.92,pow(max((c+0.055)/1.055,vec3(0)),vec3(2.4)),step(vec3(0.04045),c));
}
vec3 gammaRGB(vec3 c) {
    c=max(c,vec3(0));
    return mix(c*12.92,1.055*pow(c,vec3(1.0/2.4))-0.055,step(vec3(0.0031308),c));
}
float luma(vec3 c) { return dot(c,vec3(0.2126,0.7152,0.0722)); }
vec3 filmic(vec3 x) {
    return clamp((x*(2.51*x+0.03))/(x*(2.43*x+0.59)+0.14),0.0,1.0);
}
vec3 referenceGrade(vec3 c,vec4 grade,vec4 detail,vec3 shadowTint,vec3 highlightTint,vec2 uv) {
    float lum=luma(c);
    float chroma=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));
    // Protect saturated lamp/neon colors from the blue night shadow tint.
    float shadow=(1.0-smoothstep(0.035,0.35,lum))*(1.0-clamp(chroma*3.0,0.0,1.0));
    c*=mix(vec3(1),shadowTint,shadow)*mix(vec3(1),highlightTint,smoothstep(0.12,0.8,lum));
    c*=grade.x;
    c=mix(c,filmic(c),grade.w);
    c=mix(vec3(luma(c)),c,grade.y+detail.y*(1.0-clamp(chroma*2.0,0.0,1.0)));
    // Preserve black and avoid the hard clipping of an affine contrast curve.
    c=0.18*pow(max(c/0.18,vec3(0)),vec3(grade.z));
    float toe=luma(c);
    c+=detail.z*smoothstep(0.0,0.02,toe)*(1.0-smoothstep(0.03,0.20,toe));
    vec2 q=uv*2.0-1.0;
    c*=1.0-detail.w*smoothstep(0.2,1.6,dot(q,q));
    return max(c,vec3(0));
}

float viewDepth(vec2 uv) {
    float z=(texture(uDepth,uv).r-uDepthRange.x)/(uDepthRange.y-uDepthRange.x)*2.0-1.0;
    vec4 p=uInvProjection*vec4(uv*2.0-1.0,z,1);
    return abs(p.z/max(abs(p.w),1e-7));
}
vec3 viewPosition(vec2 uv) {
    float z=(texture(uDepth,uv).r-uDepthRange.x)/(uDepthRange.y-uDepthRange.x)*2.0-1.0;
    vec4 p=uInvProjection*vec4(uv*2.0-1.0,z,1.0);
    return p.xyz/(abs(p.w)>1e-7 ? p.w : (p.w<0.0 ? -1e-7 : 1e-7));
}
vec3 worldDirection(vec2 uv) {
    vec4 p=uInvProjection*vec4(uv*2.0-1.0,0.0,1.0);
    return normalize(mat3(uInvView)*(p.xyz/(abs(p.w)>1e-7 ? p.w : 1e-7)));
}
vec3 viewNormal(vec2 uv,vec3 p) {
    vec3 r=viewPosition(uv+vec2(uDepthTexel.x,0.0))-p, l=p-viewPosition(uv-vec2(uDepthTexel.x,0.0));
    vec3 t=viewPosition(uv+vec2(0.0,uDepthTexel.y))-p, b=p-viewPosition(uv-vec2(0.0,uDepthTexel.y));
    vec3 n=cross(dot(r,r)<dot(l,l) ? r : l,dot(t,t)<dot(b,b) ? t : b);
    if(dot(n,n)<1e-14) return vec3(0.0);
    n=normalize(n);
    return dot(n,-p)<0.0 ? -n : n;
}
float hash12(vec2 p) {
    vec3 q=fract(vec3(p.xyx)*0.1031);
    q+=dot(q,q.yzx+33.33);
    return fract((q.x+q.y)*q.z);
}
float valueNoise(vec2 p) {
    vec2 i=floor(p),f=fract(p);
    vec2 u=f*f*(3.0-2.0*f);
    return mix(mix(hash12(i),hash12(i+vec2(1,0)),u.x),mix(hash12(i+vec2(0,1)),hash12(i+vec2(1,1)),u.x),u.y);
}
// Rain drop rings on standing water, anchored to world XY (stable when the camera moves).
float ripple(vec2 p,float t) {
    vec2 g=p*1.7;vec2 cell=floor(g);vec2 f=fract(g)-0.5;
    float h=hash12(cell);
    vec2 o=vec2(hash12(cell+3.1),hash12(cell+7.7))-0.5;
    float phase=fract(t*0.9+h);
    float d=length(f-o*0.6)-phase*0.5;
    return exp(-d*d*576.0)*(1.0-phase);
}
vec4 effects() {
    if(uHasDepth==0) return vec4(0,0,0,1);
    // Depth-aware 4-tap upsample untuk mengurangi halo half-resolution.
    float center=viewDepth(vUV);
    vec2 base=floor(vUV*uEffectSize-0.5);
    vec2 fraction=fract(vUV*uEffectSize-0.5);
    vec4 sum=vec4(0);float total=0.0;
    for(int y=0;y<2;++y) for(int x=0;x<2;++x) {
        vec2 uv=(base+vec2(x,y)+0.5)/uEffectSize;
        vec2 w=mix(1.0-fraction,fraction,vec2(x,y));
        float weight=w.x*w.y*exp(-abs(viewDepth(uv)-center)/max(0.05,center*0.01));
        sum+=texture(uEffects,uv)*weight;total+=weight;
    }
    return total>1e-5 ? sum/total : vec4(0,0,0,1);
}
vec3 scene(vec2 uv) {
    vec3 c=texture(uScene,uv).rgb;return uDecodeSRGB!=0 ? linearRGB(c) : c;
}
// FXAA (Lottes, console-style): 5 taps, smooths stair-step edges and thin
// shimmering geometry without blurring flat areas.
vec3 fxaaScene(vec2 uv) {
    vec3 m=scene(uv);
    vec3 nw=scene(uv+vec2(-1.0,-1.0)*uTexel), ne=scene(uv+vec2(1.0,-1.0)*uTexel);
    vec3 sw=scene(uv+vec2(-1.0,1.0)*uTexel), se=scene(uv+vec2(1.0,1.0)*uTexel);
    float lm=luma(m),lnw=luma(nw),lne=luma(ne),lsw=luma(sw),lse=luma(se);
    float lmin=min(lm,min(min(lnw,lne),min(lsw,lse)));
    float lmax=max(lm,max(max(lnw,lne),max(lsw,lse)));
    if(lmax-lmin<max(0.0312,lmax*0.125)) return m;
    vec2 dir=vec2(-((lnw+lne)-(lsw+lse)),(lnw+lsw)-(lne+lse));
    float reduce=max((lnw+lne+lsw+lse)*0.03125,1.0/128.0);
    dir=clamp(dir/(min(abs(dir.x),abs(dir.y))+reduce),vec2(-8.0),vec2(8.0))*uTexel;
    vec3 a=0.5*(scene(uv+dir*(1.0/3.0-0.5))+scene(uv+dir*(2.0/3.0-0.5)));
    vec3 b=a*0.5+0.25*(scene(uv-dir*0.5)+scene(uv+dir*0.5));
    float lb=luma(b);
    return (lb<lmin||lb>lmax) ? a : b;
}
// Wet asphalt and puddles on flat ground. Returns the reflection multiplier.
float wetSurface(inout vec3 c) {
    vec3 p=viewPosition(vUV);
    float distance=length(p);
    vec3 n=mat3(uInvView)*viewNormal(vUV,p);
    float flatness=smoothstep(0.80,0.95,n.z)*(1.0-smoothstep(60.0,140.0,distance));
    if(flatness<=0.0) return 1.0;
    vec3 world=(uInvView*vec4(p,1.0)).xyz;
    float noise=valueNoise(world.xy*0.18)*0.65+valueNoise(world.xy*0.55+17.3)*0.35;
    float puddle=smoothstep(1.0-uWet.z,1.0-uWet.z+0.12,noise)*uWet.x*flatness;
    float damp=uWet.x*flatness;
    c*=mix(1.0,0.72,damp);   // wet asphalt is darker
    c=mix(c,c*0.55,puddle);  // standing water hides the albedo
    vec3 toEye=normalize(mat3(uInvView)*(-p));
    float fresnel=0.02+0.98*pow(1.0-clamp(toEye.z,0.0,1.0),5.0);
    vec3 skyColour=mix(uSkyHorizon.rgb,uSkyZenith.rgb,0.3);
    float rings=uWet.y>0.01 ? ripple(world.xy,uTime)+ripple(world.xy+vec2(0.37,0.71),uTime*1.13) : 0.0;
    c+=skyColour*(fresnel*puddle*0.6+rings*puddle*uWet.y*0.25);
    return 1.0+uWet.w*puddle+0.5*damp;
}
// Realtime sky: GTA's own sky/clouds keep their brightness structure, the
// hue follows the time/weather model, plus forward scattering around the sun.
vec3 skyGrade(vec3 c) {
    vec3 d=worldDirection(vUV);
    float h=d.z;
    vec3 model=mix(uSkyHorizon.rgb,uSkyZenith.rgb,smoothstep(-0.02,0.45,h));
    float l=luma(c);
    c=mix(c,model*(l/max(luma(model),1e-4)),uSkyZenith.w);
    c=mix(c,uSkyHorizon.rgb*(l/max(luma(uSkyHorizon.rgb),1e-4)),uSkyHorizon.w*(1.0-smoothstep(0.0,0.35,h)));
    float mu=max(dot(d,uSunDirection.xyz),0.0);
    c+=uSunColor.rgb*(pow(mu,48.0)*0.55+pow(mu,6.0)*0.18)*uSunColor.w;
    return c;
}
void main() {
    vec4 src=texture(uScene,vUV);
    vec3 c=uFXAA!=0 ? fxaaScene(vUV) : (uDecodeSRGB!=0 ? linearRGB(src.rgb) : src.rgb);
    vec3 local=(scene(vUV+vec2(uTexel.x,0))+scene(vUV-vec2(uTexel.x,0))
        +scene(vUV+vec2(0,uTexel.y))+scene(vUV-vec2(0,uTexel.y)))*0.25;
    c=max(c+clamp((luma(c)-luma(local))*uDetail.x,-0.035,0.035),vec3(0));
    vec4 fx=effects();
    bool geometry=uHasDepth!=0 && abs(texture(uDepth,vUV).r-uClearDepth)>0.0000002;
    float reflection=geometry && uWet.x>0.01 ? wetSurface(c) : 1.0;
    c=c*fx.a+fx.rgb*reflection;
    if(geometry) {
        float distance=max(viewDepth(vUV)-8.0,0.0);
        c=mix(c,uFog.rgb,clamp(1.0-exp(-distance*uFog.a),0.0,0.78));
    } else if(uHasDepth!=0 && uSkyZenith.w+uSkyHorizon.w+uSunColor.w>0.0) {
        c=skyGrade(c);
    }
    vec3 bloom=texture(uBloom0,vUV).rgb*0.50+texture(uBloom1,vUV).rgb*0.30+texture(uBloom2,vUV).rgb*0.20;
    c+=bloom*uBloomDirt.x*(1.0+texture(uDirt,vUV).r*uBloomDirt.y);
    c+=texture(uAtmosphere,vUV).rgb;
    for(int i=0;i<4;++i) {
        if(i>=uLightCount) break;
        vec2 d=(vUV-uLightPosition[i].xy)*vec2(uAspect,1.0);
        float r=max(uLightPosition[i].z,0.001);
        float glow=exp(-dot(d,d)/(r*r));
        float pulse=1.0+uLightColor[i].a*sin(uTime*0.6+float(i)*1.7);
        c+=uLightColor[i].rgb*(uLightPosition[i].w*glow*pulse);
    }
    c=referenceGrade(c,uGrade,uDetail,uShadowTint,uHighlightTint,vUV);
    outColor=vec4(uEncodeSRGB!=0 ? gammaRGB(c) : c,src.a);
}
)GLSL";
inline constexpr char kAtmosphere[] = R"GLSL(#version 300 es
precision highp float;
precision highp sampler2D;
in highp vec2 vUV;
layout(location=0) out vec4 outColor;
#define FX_TEXTURE texture
#define FX_DEPTH 1
vec3 linearRGB(vec3 c) {
    return mix(c/12.92,pow(max((c+0.055)/1.055,vec3(0)),vec3(2.4)),step(vec3(0.04045),c));
}
vec3 gammaRGB(vec3 c) {
    c=max(c,vec3(0));
    return mix(c*12.92,1.055*pow(c,vec3(1.0/2.4))-0.055,step(vec3(0.0031308),c));
}
float luma(vec3 c) { return dot(c,vec3(0.2126,0.7152,0.0722)); }
vec3 filmic(vec3 x) {
    return clamp((x*(2.51*x+0.03))/(x*(2.43*x+0.59)+0.14),0.0,1.0);
}
vec3 referenceGrade(vec3 c,vec4 grade,vec4 detail,vec3 shadowTint,vec3 highlightTint,vec2 uv) {
    float lum=luma(c);
    float chroma=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));
    // Protect saturated lamp/neon colors from the blue night shadow tint.
    float shadow=(1.0-smoothstep(0.035,0.35,lum))*(1.0-clamp(chroma*3.0,0.0,1.0));
    c*=mix(vec3(1),shadowTint,shadow)*mix(vec3(1),highlightTint,smoothstep(0.12,0.8,lum));
    c*=grade.x;
    c=mix(c,filmic(c),grade.w);
    c=mix(vec3(luma(c)),c,grade.y+detail.y*(1.0-clamp(chroma*2.0,0.0,1.0)));
    // Preserve black and avoid the hard clipping of an affine contrast curve.
    c=0.18*pow(max(c/0.18,vec3(0)),vec3(grade.z));
    float toe=luma(c);
    c+=detail.z*smoothstep(0.0,0.02,toe)*(1.0-smoothstep(0.03,0.20,toe));
    vec2 q=uv*2.0-1.0;
    c*=1.0-detail.w*smoothstep(0.2,1.6,dot(q,q));
    return max(c,vec3(0));
}

uniform sampler2D uScene;
uniform vec2 uTexel;
uniform vec4 uSun; // sun UV, shaft strength, flare strength.
uniform float uAspect;
uniform int uDecodeSRGB;
#ifdef FX_DEPTH
uniform sampler2D uDepth;
uniform int uHasDepth;
uniform float uClearDepth;
// 1 on sky pixels. Buildings, trees, vehicles, peds and SA-MP objects write
// depth, so they block the rays instead of glowing themselves.
float skyAt(vec2 uv) {
    if(uHasDepth==0) return 1.0;
    return abs(FX_TEXTURE(uDepth,uv).r-uClearDepth)<0.0000002 ? 1.0 : 0.0;
}
float brightStart() { return uHasDepth!=0 ? 0.45 : 0.65; }
#else
float skyAt(vec2 uv) { return 1.0; }
float brightStart() { return 0.65; }
#endif
vec3 highlightAt(vec2 uv) {
    vec3 c=FX_TEXTURE(uScene,uv).rgb;
    if(uDecodeSRGB!=0) c=linearRGB(c);
    float bright=max(c.r,max(c.g,c.b));
    return c*smoothstep(brightStart(),0.98,bright)*skyAt(uv);
}
vec3 sunEffects(vec2 uv) {
    if(uSun.z+uSun.w<0.0001) return vec3(0);
    // Visibility = share of open, bright sky in a small disc around the sun.
    // Fractional, so the rays fade while the sun slides behind an edge.
    vec2 centre=clamp(uSun.xy,vec2(0.002),vec2(0.998));
    vec3 light=vec3(0);float open=0.0;
    for(int i=0;i<12;++i) {
        float a=float(i)*0.5235988;
        vec2 p=clamp(centre+vec2(cos(a),sin(a))*vec2(1.0/uAspect,1.0)*0.018*(0.5+0.5*mod(float(i),2.0)),vec2(0.001),vec2(0.999));
        light+=highlightAt(p);open+=skyAt(p);
    }
    light/=12.0;open/=12.0;
    float visibility=smoothstep(0.20,0.85,max(light.r,max(light.g,light.b)))*open;
    vec2 delta=(uSun.xy-uv)*(0.88/24.0);
    vec2 p=uv;vec3 rays=vec3(0);float decay=1.0;
    for(int i=0;i<24;++i) {
        p+=delta;rays+=highlightAt(clamp(p,vec2(0.001),vec2(0.999)))*decay;decay*=0.965;
    }
    vec2 sunDelta=(uv-uSun.xy)*vec2(uAspect,1);
    float halo=exp(-dot(sunDelta,sunDelta)/0.025);
    vec2 axis=vec2(0.5)-uSun.xy;
    vec2 ghostDelta=(uv-(vec2(0.5)+axis*0.55))*vec2(uAspect,1);
    float ghost=exp(-dot(ghostDelta,ghostDelta)/0.0018);
    vec3 glow=visibility*(rays*(uSun.z/24.0)+light*uSun.w*halo
        +vec3(0.40,0.28,0.12)*ghost*uSun.w*0.22);
    // Soft limit: added light approaches 1 but never washes the frame white.
    return glow/(1.0+luma(glow));
}

void main() { outColor=vec4(sunEffects(vUV),1); }
)GLSL";
inline constexpr char kCompatVertex[] = R"GLSL(#version 100
attribute vec2 aPosition;
varying highp vec2 vUV;
void main() { vUV=aPosition*0.5+0.5;gl_Position=vec4(aPosition,0,1); }
)GLSL";
inline constexpr char kCompatBloom[] = R"GLSL(#version 100
precision highp float;
varying highp vec2 vUV;
uniform sampler2D uSource;
uniform vec2 uDirection;
uniform int uExtract;
uniform int uDecodeSRGB;
uniform vec2 uThresholdKnee;
vec3 linearRGB(vec3 c) {
    return mix(c/12.92,pow(max((c+0.055)/1.055,vec3(0)),vec3(2.4)),step(vec3(0.04045),c));
}
vec3 gammaRGB(vec3 c) {
    c=max(c,vec3(0));
    return mix(c*12.92,1.055*pow(c,vec3(1.0/2.4))-0.055,step(vec3(0.0031308),c));
}
float luma(vec3 c) { return dot(c,vec3(0.2126,0.7152,0.0722)); }
vec3 filmic(vec3 x) {
    return clamp((x*(2.51*x+0.03))/(x*(2.43*x+0.59)+0.14),0.0,1.0);
}
vec3 referenceGrade(vec3 c,vec4 grade,vec4 detail,vec3 shadowTint,vec3 highlightTint,vec2 uv) {
    float lum=luma(c);
    float chroma=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));
    // Protect saturated lamp/neon colors from the blue night shadow tint.
    float shadow=(1.0-smoothstep(0.035,0.35,lum))*(1.0-clamp(chroma*3.0,0.0,1.0));
    c*=mix(vec3(1),shadowTint,shadow)*mix(vec3(1),highlightTint,smoothstep(0.12,0.8,lum));
    c*=grade.x;
    c=mix(c,filmic(c),grade.w);
    c=mix(vec3(luma(c)),c,grade.y+detail.y*(1.0-clamp(chroma*2.0,0.0,1.0)));
    // Preserve black and avoid the hard clipping of an affine contrast curve.
    c=0.18*pow(max(c/0.18,vec3(0)),vec3(grade.z));
    float toe=luma(c);
    c+=detail.z*smoothstep(0.0,0.02,toe)*(1.0-smoothstep(0.03,0.20,toe));
    vec2 q=uv*2.0-1.0;
    c*=1.0-detail.w*smoothstep(0.2,1.6,dot(q,q));
    return max(c,vec3(0));
}

vec3 tap(vec2 uv) {
    vec3 c=texture2D(uSource,uv).rgb;
    if(uDecodeSRGB!=0) c=linearRGB(c);
    if(uExtract!=0) {
        float b=max(c.r,max(c.g,c.b)),k=max(uThresholdKnee.y,0.001);
        float soft=clamp(b-uThresholdKnee.x+k,0.0,2.0*k);
        c*=max(b-uThresholdKnee.x,soft*soft/(4.0*k))/max(b,0.001);
    }
    return c;
}
void main() {
    vec3 c=tap(vUV)*0.227027;
    c+=(tap(vUV+uDirection*1.384615)+tap(vUV-uDirection*1.384615))*0.316216;
    c+=(tap(vUV+uDirection*3.230769)+tap(vUV-uDirection*3.230769))*0.070270;
    gl_FragColor=vec4(c,1);
}
)GLSL";
inline constexpr char kCompatComposite[] = R"GLSL(#version 100
precision highp float;
varying highp vec2 vUV;
uniform sampler2D uScene,uBloom0,uBloom1,uAtmosphere;
uniform int uDecodeSRGB,uEncodeSRGB;
uniform vec4 uGrade,uDetail;
uniform vec3 uShadowTint,uHighlightTint;
uniform vec2 uTexel,uBloomDirt;
vec3 linearRGB(vec3 c) {
    return mix(c/12.92,pow(max((c+0.055)/1.055,vec3(0)),vec3(2.4)),step(vec3(0.04045),c));
}
vec3 gammaRGB(vec3 c) {
    c=max(c,vec3(0));
    return mix(c*12.92,1.055*pow(c,vec3(1.0/2.4))-0.055,step(vec3(0.0031308),c));
}
float luma(vec3 c) { return dot(c,vec3(0.2126,0.7152,0.0722)); }
vec3 filmic(vec3 x) {
    return clamp((x*(2.51*x+0.03))/(x*(2.43*x+0.59)+0.14),0.0,1.0);
}
vec3 referenceGrade(vec3 c,vec4 grade,vec4 detail,vec3 shadowTint,vec3 highlightTint,vec2 uv) {
    float lum=luma(c);
    float chroma=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));
    // Protect saturated lamp/neon colors from the blue night shadow tint.
    float shadow=(1.0-smoothstep(0.035,0.35,lum))*(1.0-clamp(chroma*3.0,0.0,1.0));
    c*=mix(vec3(1),shadowTint,shadow)*mix(vec3(1),highlightTint,smoothstep(0.12,0.8,lum));
    c*=grade.x;
    c=mix(c,filmic(c),grade.w);
    c=mix(vec3(luma(c)),c,grade.y+detail.y*(1.0-clamp(chroma*2.0,0.0,1.0)));
    // Preserve black and avoid the hard clipping of an affine contrast curve.
    c=0.18*pow(max(c/0.18,vec3(0)),vec3(grade.z));
    float toe=luma(c);
    c+=detail.z*smoothstep(0.0,0.02,toe)*(1.0-smoothstep(0.03,0.20,toe));
    vec2 q=uv*2.0-1.0;
    c*=1.0-detail.w*smoothstep(0.2,1.6,dot(q,q));
    return max(c,vec3(0));
}

vec3 scene(vec2 uv) {
    vec3 c=texture2D(uScene,uv).rgb;return uDecodeSRGB!=0 ? linearRGB(c) : c;
}
void main() {
    vec4 src=texture2D(uScene,vUV);vec3 c=scene(vUV);
    vec3 local=(scene(vUV+vec2(uTexel.x,0))+scene(vUV-vec2(uTexel.x,0))
        +scene(vUV+vec2(0,uTexel.y))+scene(vUV-vec2(0,uTexel.y)))*0.25;
    float edge=clamp((luma(c)-luma(local))*uDetail.x,-0.035,0.035);
    c=max(c+edge,vec3(0));
    vec3 bloom=texture2D(uBloom0,vUV).rgb*0.65+texture2D(uBloom1,vUV).rgb*0.35;
    float dust=pow(max(0.0,sin(vUV.x*137.0)*sin(vUV.y*111.0)),12.0);
    c+=bloom*uBloomDirt.x*(1.0+dust*uBloomDirt.y)+texture2D(uAtmosphere,vUV).rgb;
    c=referenceGrade(c,uGrade,uDetail,uShadowTint,uHighlightTint,vUV);
    gl_FragColor=vec4(uEncodeSRGB!=0 ? gammaRGB(c) : c,src.a);
}
)GLSL";
inline constexpr char kCompatAtmosphere[] = R"GLSL(#version 100
precision highp float;
varying highp vec2 vUV;
#define FX_TEXTURE texture2D
vec3 linearRGB(vec3 c) {
    return mix(c/12.92,pow(max((c+0.055)/1.055,vec3(0)),vec3(2.4)),step(vec3(0.04045),c));
}
vec3 gammaRGB(vec3 c) {
    c=max(c,vec3(0));
    return mix(c*12.92,1.055*pow(c,vec3(1.0/2.4))-0.055,step(vec3(0.0031308),c));
}
float luma(vec3 c) { return dot(c,vec3(0.2126,0.7152,0.0722)); }
vec3 filmic(vec3 x) {
    return clamp((x*(2.51*x+0.03))/(x*(2.43*x+0.59)+0.14),0.0,1.0);
}
vec3 referenceGrade(vec3 c,vec4 grade,vec4 detail,vec3 shadowTint,vec3 highlightTint,vec2 uv) {
    float lum=luma(c);
    float chroma=max(c.r,max(c.g,c.b))-min(c.r,min(c.g,c.b));
    // Protect saturated lamp/neon colors from the blue night shadow tint.
    float shadow=(1.0-smoothstep(0.035,0.35,lum))*(1.0-clamp(chroma*3.0,0.0,1.0));
    c*=mix(vec3(1),shadowTint,shadow)*mix(vec3(1),highlightTint,smoothstep(0.12,0.8,lum));
    c*=grade.x;
    c=mix(c,filmic(c),grade.w);
    c=mix(vec3(luma(c)),c,grade.y+detail.y*(1.0-clamp(chroma*2.0,0.0,1.0)));
    // Preserve black and avoid the hard clipping of an affine contrast curve.
    c=0.18*pow(max(c/0.18,vec3(0)),vec3(grade.z));
    float toe=luma(c);
    c+=detail.z*smoothstep(0.0,0.02,toe)*(1.0-smoothstep(0.03,0.20,toe));
    vec2 q=uv*2.0-1.0;
    c*=1.0-detail.w*smoothstep(0.2,1.6,dot(q,q));
    return max(c,vec3(0));
}

uniform sampler2D uScene;
uniform vec2 uTexel;
uniform vec4 uSun; // sun UV, shaft strength, flare strength.
uniform float uAspect;
uniform int uDecodeSRGB;
#ifdef FX_DEPTH
uniform sampler2D uDepth;
uniform int uHasDepth;
uniform float uClearDepth;
// 1 on sky pixels. Buildings, trees, vehicles, peds and SA-MP objects write
// depth, so they block the rays instead of glowing themselves.
float skyAt(vec2 uv) {
    if(uHasDepth==0) return 1.0;
    return abs(FX_TEXTURE(uDepth,uv).r-uClearDepth)<0.0000002 ? 1.0 : 0.0;
}
float brightStart() { return uHasDepth!=0 ? 0.45 : 0.65; }
#else
float skyAt(vec2 uv) { return 1.0; }
float brightStart() { return 0.65; }
#endif
vec3 highlightAt(vec2 uv) {
    vec3 c=FX_TEXTURE(uScene,uv).rgb;
    if(uDecodeSRGB!=0) c=linearRGB(c);
    float bright=max(c.r,max(c.g,c.b));
    return c*smoothstep(brightStart(),0.98,bright)*skyAt(uv);
}
vec3 sunEffects(vec2 uv) {
    if(uSun.z+uSun.w<0.0001) return vec3(0);
    // Visibility = share of open, bright sky in a small disc around the sun.
    // Fractional, so the rays fade while the sun slides behind an edge.
    vec2 centre=clamp(uSun.xy,vec2(0.002),vec2(0.998));
    vec3 light=vec3(0);float open=0.0;
    for(int i=0;i<12;++i) {
        float a=float(i)*0.5235988;
        vec2 p=clamp(centre+vec2(cos(a),sin(a))*vec2(1.0/uAspect,1.0)*0.018*(0.5+0.5*mod(float(i),2.0)),vec2(0.001),vec2(0.999));
        light+=highlightAt(p);open+=skyAt(p);
    }
    light/=12.0;open/=12.0;
    float visibility=smoothstep(0.20,0.85,max(light.r,max(light.g,light.b)))*open;
    vec2 delta=(uSun.xy-uv)*(0.88/24.0);
    vec2 p=uv;vec3 rays=vec3(0);float decay=1.0;
    for(int i=0;i<24;++i) {
        p+=delta;rays+=highlightAt(clamp(p,vec2(0.001),vec2(0.999)))*decay;decay*=0.965;
    }
    vec2 sunDelta=(uv-uSun.xy)*vec2(uAspect,1);
    float halo=exp(-dot(sunDelta,sunDelta)/0.025);
    vec2 axis=vec2(0.5)-uSun.xy;
    vec2 ghostDelta=(uv-(vec2(0.5)+axis*0.55))*vec2(uAspect,1);
    float ghost=exp(-dot(ghostDelta,ghostDelta)/0.0018);
    vec3 glow=visibility*(rays*(uSun.z/24.0)+light*uSun.w*halo
        +vec3(0.40,0.28,0.12)*ghost*uSun.w*0.22);
    // Soft limit: added light approaches 1 but never washes the frame white.
    return glow/(1.0+luma(glow));
}

void main() { gl_FragColor=vec4(sunEffects(vUV),1); }
)GLSL";
}
